-- =================================================================
-- 🚀 PROJECT NOCTURNA: SUPABASE CLOUD SCHEMA
-- =================================================================

-- 1. ENABLE POSTGIS
-- (Ensure this is also enabled in Dashboard > Database > Extensions)
CREATE EXTENSION IF NOT EXISTS postgis;

-- =================================================================
-- CLEANUP (Reset Schema for fresh deployment)
-- =================================================================
DROP TABLE IF EXISTS zonal_time_series CASCADE;
DROP TABLE IF EXISTS analysis_grid CASCADE;
DROP TABLE IF EXISTS light_measurements CASCADE;
DROP TABLE IF EXISTS public_lighting CASCADE;
DROP TABLE IF EXISTS protected_areas CASCADE;
DROP TABLE IF EXISTS admin_boundaries CASCADE;

-- =================================================================
-- A. REFERENCE LAYERS
-- =================================================================

-- 1. ADMINISTRATIVE BOUNDARIES
CREATE TABLE admin_boundaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(50),
    parent_id BIGINT REFERENCES admin_boundaries(id),
    population INT,
    gdp_estimate DECIMAL(15,2),
    geom GEOMETRY(MultiPolygon, 4326)
);

-- 2. PROTECTED AREAS
CREATE TABLE protected_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    category VARCHAR(50),
    iucn_cat VARCHAR(10),
    sensitivity_threshold DECIMAL(5,2),
    buffer_radius_km INT DEFAULT 50,
    geom GEOMETRY(MultiPolygon, 4326)
);

-- =================================================================
-- B. OBSERVATION LAYERS (Realtime Enabled)
-- =================================================================

-- 3. MEASUREMENTS (Citizen Science)
CREATE TABLE light_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID DEFAULT auth.uid(), -- Links to Supabase Auth user if logged in
    sqm_reading DECIMAL(4, 2),
    bortle_class INT,
    device_type VARCHAR(50),
    measured_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    is_research_grade BOOLEAN DEFAULT FALSE,
    geom GEOMETRY(Point, 4326)
);

-- 4. STREETLIGHTS
CREATE TABLE public_lighting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),
    wattage INT,
    shielded BOOLEAN DEFAULT FALSE,
    geom GEOMETRY(Point, 4326)
);

-- =================================================================
-- C. ANALYTICAL LAYERS
-- =================================================================

-- 5. ANALYSIS GRID (Hotspots)
CREATE TABLE analysis_grid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cell_id VARCHAR(50) UNIQUE,
    land_cover_class VARCHAR(50),
    is_urban BOOLEAN,
    population_density INT,
    mean_radiance_2024 DECIMAL(10,4),
    trend_slope DECIMAL(10,4),
    trend_significance DECIMAL(5,4),
    risk_level VARCHAR(20),
    geom GEOMETRY(Polygon, 4326)
);

-- 6. ZONAL TIME SERIES
CREATE TABLE zonal_time_series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT REFERENCES admin_boundaries(id),
    month_date DATE,
    avg_radiance DECIMAL(10,4),
    total_lit_area_km2 DECIMAL(10,2)
);

-- =================================================================
-- D. SECURITY (Row Level Security)
-- =================================================================

-- Enable RLS on all tables
ALTER TABLE admin_boundaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE protected_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE light_measurements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_lighting ENABLE ROW LEVEL SECURITY;
ALTER TABLE analysis_grid ENABLE ROW LEVEL SECURITY;
ALTER TABLE zonal_time_series ENABLE ROW LEVEL SECURITY;

-- POLICIES:
-- 1. PUBLIC READ: Everyone can see the map layers
CREATE POLICY "Public Read Access" ON admin_boundaries FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON protected_areas FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON light_measurements FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON public_lighting FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON analysis_grid FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON zonal_time_series FOR SELECT USING (true);

-- 2. PUBLIC INSERT: Allow users to submit measurements (You can restrict this to auth users later)
CREATE POLICY "Allow Insert Measurements" ON light_measurements FOR INSERT WITH CHECK (true);

-- Note: No specific policy needed for Service Role (your backend scripts), as it bypasses RLS by default.

-- =================================================================
-- E. REALTIME & INDEXING
-- =================================================================

-- Enable Realtime for Measurements (Live Map Updates)
alter publication supabase_realtime add table light_measurements;

-- Spatial Indexes (GIST) for fast map queries
CREATE INDEX idx_admin_geom ON admin_boundaries USING GIST (geom);
CREATE INDEX idx_protected_geom ON protected_areas USING GIST (geom);
CREATE INDEX idx_grid_geom ON analysis_grid USING GIST (geom);
CREATE INDEX idx_measurements_geom ON light_measurements USING GIST (geom);

-- =================================================================
-- F. GLOBAL SEED DATA
-- =================================================================

-- 1. Global Cities (Admin Boundaries)
INSERT INTO admin_boundaries (name, type, population, geom) VALUES 
('Lahore', 'Metropolis', 11130000, ST_GeomFromText('MULTIPOLYGON(((74.2 31.4, 74.5 31.4, 74.5 31.7, 74.2 31.7, 74.2 31.4)))', 4326)),
('New York City', 'Metropolis', 8419000, ST_GeomFromText('MULTIPOLYGON(((-74.25 40.5, -73.7 40.5, -73.7 40.9, -74.25 40.9, -74.25 40.5)))', 4326)),
('London', 'Metropolis', 8982000, ST_GeomFromText('MULTIPOLYGON(((-0.5 51.3, 0.3 51.3, 0.3 51.7, -0.5 51.7, -0.5 51.3)))', 4326));

-- 2. Measurements (Global Points)
INSERT INTO light_measurements (sqm_reading, bortle_class, notes, is_research_grade, geom) VALUES
(18.2, 8, 'Lahore Urban Center', false, ST_SetSRID(ST_Point(74.3587, 31.5204), 4326)),
(16.2, 9, 'Times Square, NYC', true, ST_SetSRID(ST_Point(-73.9855, 40.7580), 4326)),
(21.8, 2, 'Aoraki Mackenzie, NZ', true, ST_SetSRID(ST_Point(170.15, -43.73), 4326));

-- 3. Analysis Grid (Mock Hotspots for Demo)
INSERT INTO analysis_grid (cell_id, mean_radiance_2024, risk_level, geom) VALUES
('GRID_LHR_001', 55.2, 'Critical', ST_SetSRID(ST_MakeEnvelope(74.3, 31.5, 74.31, 31.51, 4326), 4326)),
('GRID_NYC_001', 85.5, 'Critical', ST_SetSRID(ST_MakeEnvelope(-74.00, 40.71, -73.99, 40.72, 4326), 4326));