version: '3.8'

services:
  db:
    image: docker.io/postgis/postgis:15-3.3
    container_name: projectnocturna_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  geoserver:
    image: docker.io/kartoza/geoserver:2.24.1
    container_name: projectnocturna_geoserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: "*"
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir:Z
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectnocturna_app
    restart: always
    ports:
      - "3000:3000"
    command: sh -c "npm run seed && npm start"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      NODE_ENV: production
      ADMIN_SECRET: ${ADMIN_SECRET}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}

  # --- NEW: n8n Workflow Automation ---
  n8n:
    image: docker.io/n8nio/n8n:latest
    container_name: projectnocturna_n8n
    restart: always
    ports:
      - "5678:5678"  # Access UI at http://localhost:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Karachi # Adjust to your timezone
      - TZ=Asia/Karachi
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n # Persist workflows
    depends_on:
      db:
        condition: service_healthy

# ... (other services remain the same) ...

  n8n:
    image: docker.io/n8nio/n8n:latest
    container_name: projectnocturna_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Karachi
      - TZ=Asia/Karachi
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      # Mount your specific workflow file so n8n can see it
      - ./WebGIS_ActionBot_Final_Fixed.json:/tmp/workflow.json:Z
    depends_on:
      db:
        condition: service_healthy
    # This command imports the workflow, then starts the server
    command: >
      /bin/sh -c "n8n import:workflow --input=/tmp/workflow.json && n8n start"


volumes:
  postgres_data:
  n8n_data: # Define the new volume